"""Add freebies relationship to Dev

Revision ID: 58de0c1aa4cc
Revises: fa0b8465e187
Create Date: 2023-12-06 15:41:07.352450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58de0c1aa4cc'
down_revision = 'fa0b8465e187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
