"""Add freebies relationship to company

Revision ID: fa0b8465e187
Revises: 2547436a6056
Create Date: 2023-12-06 15:39:11.202762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0b8465e187'
down_revision = '2547436a6056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
